#!/bin/bash

sed -i '177d' /etc/locale.gen
sed -i "177i #en_US.UTF-8 UTF-8" /etc/locale.gen

sed -i '200d' /etc/locale.gen
sed -i "200i es_ES.UTF-8 UTF-8" /etc/locale.gen

locale-gen

echo LANG=es_ES.UTF-8 > /etc/locale.conf
export LANG=es_ES.UTF-8
locale-gen
export LANG=es_ES.UTF-8
echo ""
sleep 3
clear

echo "print devices" | parted | grep /dev/ | awk '{if (NR!=1) {print}}'
echo ''
read -p "Introduce tu disco a instalar Arch: " disco

echo ''
echo "Selección de Disco: $disco"
sleep 3
echo ''

uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

if [ $uefi == 1 ]
then
	echo "Sistema UEFI"

else
	echo "Sistema BIOS"
fi

#sgdisk --zap-all ${disk} && parted ${disk} mklabel gpt && \
#sgdisk ${disk} -n=1:0:+1G -t=1:ef00 && \
#sgdisk ${disk} -n=2:0:+${swapsize} -t=2:8200 && \
#sgdisk ${disk} -n=3:0:0 && \
#fdisk -l ${disk} > /tmp/partitions && \
#cat /tmp/partitions" 13 100

#partitions="$(cat /tmp/partitions | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"

#echo $partitions | awk -F ' ' '{print $1}' >  boot-efi
#echo $partitions | awk -F ' ' '{print $2}' >  swap-efi
#echo $partitions | awk -F ' ' '{print $3}' >  root-efi


#--prgbox "sgdisk --zap-all ${disk} && \
#(echo o; echo n; echo p; echo 1; echo ""; echo +250M; echo n; echo p; echo 2; echo ""; echo +${swapsize}; echo n; echo p; echo 3; echo ""; echo ""; echo t; echo 2; echo 82; echo a; echo 1; echo w; echo q) | fdisk ${disk} && \
#fdisk -l ${disk} > /tmp/partitions && \
#cat /tmp/partitions" 13 100