#!/bin/bash

#Sistema en español en liveCD
clear
echo ""
echo "Sistema en español"
echo ""
echo "es_ES.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo LANG=es_ES.UTF-8 > /etc/locale.conf
export LANG=es_ES.UTF-8
echo ""
sleep 3

#Actualización de llaves y mirroslist
clear
pacman -Sy archlinux-keyring --noconfirm 
clear
pacman -Sy reflector python rsync --noconfirm 
sleep 3
clear
echo ""
echo "Actualizando lista de MirrorList"
echo ""
reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
clear
cat /etc/pacman.d/mirrorlist
sleep 3
clear

#Disco
echo "print devices" | parted | grep /dev/ | awk '{if (NR!=1) {print}}'
echo ''
read -p "Introduce tu disco a instalar Arch: " disco

echo ''
echo "Selección de Disco: $disco"
sleep 3
echo ''

uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

if [ $uefi == 1 ]
then
	clear
	echo "Sistema UEFI"
	echo ""

	#Metodo con EFI - SWAP - ROOT - HOME
	sgdisk --zap-all ${disco}
	parted ${disco} mklabel gpt
	sgdisk ${disco} -n=1:0:+100M -t=1:ef00
	sgdisk ${disco} -n=2:0:+4G -t=2:8200
	sgdisk ${disco} -n=3:0:+50G -t=3:8300
	sgdisk ${disco} -n=4:0:0
	fdisk -l ${disco} > /tmp/partitions
	echo ""
	cat /tmp/partitions
	sleep 3

	partitions="$(cat /tmp/partitions | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"

	boot-efi="$(echo $partitions | awk -F ' ' '{print $1}')"
	swap-efi="$(echo $partitions | awk -F ' ' '{print $2}')"  
	root-efi="$(echo $partitions | awk -F ' ' '{print $3}')"
	home-efi="$(echo $partitions | awk -F ' ' '{print $4}')"

	echo ""
	echo ${boot-efi}
	echo ${swap-efi}
	echo ${root-efi}
	echo ${home-efi}


#---Metodo con EFI - SWAP - ROOT--------
#	sgdisk --zap-all ${disco}
#	parted ${disco} mklabel gpt
#	sgdisk ${disco} -n=1:0:+100M -t=1:ef00
#	sgdisk ${disco} -n=2:0:+4G -t=2:8200
#	sgdisk ${disco} -n=3:0:0
#	fdisk -l ${disco} > /tmp/partitions
#	echo ""
#	cat /tmp/partitions
#	sleep 3
#
#	partitions="$(cat /tmp/partitions | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
#
#	boot-efi="$(echo $partitions | awk -F ' ' '{print $1}')"
#	swap-efi="$(echo $partitions | awk -F ' ' '{print $2}')"  
#	root-efi="$(echo $partitions | awk -F ' ' '{print $3}')"
#
#	echo ""
#	echo $boot-efi
#	echo $swap-efi
#	echo $root-efi


else
	echo "Sistema BIOS"
fi



#--prgbox "sgdisk --zap-all ${disk} && \
#(echo o; echo n; echo p; echo 1; echo ""; echo +250M; echo n; echo p; echo 2; echo ""; echo +${swapsize}; echo n; echo p; echo 3; echo ""; echo ""; echo t; echo 2; echo 82; echo a; echo 1; echo w; echo q) | fdisk ${disk} && \
#fdisk -l ${disk} > /tmp/partitions && \
#cat /tmp/partitions" 13 100